prepare:
  dir: data/prepare
  train_file: data_train.csv
  val_file: data_val.csv
  test_file: data_test.csv

train:
  dir: model
  random_state: 0
  max_depth: 15
  max_features: sqrt
  min_samples_split: 5

evaluate:
  dir: evaluation